/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.eltex;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class App {
    public static void main(String[] args) throws IOException {
        User user = new User("Ivan", "Ivanov");
        Manager mg = new Manager("Ivan", "Ivanov", 3);
        Coder cod = new Coder("Vasy", "Petrov", false);
        System.out.println(user.toString());
        System.out.println(mg.toString());
        System.out.println(cod.toString());

        Map<String, Object> map = new HashMap();
        map.put("user", user);
        map.put("coder", cod);
        map.put("manager", mg);


        ObjectMapper mapper = new ObjectMapper();
        mapper.writeValue(new File("result.json"), map);

        /*User user1 = mapper.readValue(new File("result.json"), User.class);
        System.out.println(user1.toString());*/
    }
}
