/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.eltex;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello Java");

        Scanner in = new Scanner(System.in);
        Integer a = Integer.valueOf(in.nextLine());
        Integer b = Integer.valueOf(in.nextLine());
        String op = in.nextLine();

        if (op.equals("+")) {
            System.out.println(a + b);
        } else if (op.equals("-")) {
            System.out.println(a - b);
        }
    }
}